name: Push-to-EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: check out
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Create a production build
      run: npm run build

    - name: Deploy the prod build to my EC2 instance
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
        SCRIPT_AFTER: |
          sudo pm2 stop 0
          cd /home/ubuntu/build && sudo pm2 start server.js
          sudo systemctl restart
